//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod oauth;
pub mod orders;
pub mod permission;
pub mod picture;
pub mod real_name;
pub mod share;
pub mod user;
pub mod user_picture;
