//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(column_name = "outTradeNo", primary_key, auto_increment = false)]
    pub out_trade_no: String,
    pub uid: i64,
    pub subject: String,
    #[sea_orm(column_name = "tradeNo")]
    pub trade_no: Option<String>,
    #[sea_orm(column_name = "totalAmount")]
    pub total_amount: i64,
    #[sea_orm(column_name = "receiptAmount")]
    pub receipt_amount: Option<i64>,
    #[sea_orm(column_name = "payPlatform")]
    pub pay_platform: i32,
    #[sea_orm(column_name = "tradeStatus")]
    pub trade_status: i32,
    #[sea_orm(column_name = "createTime")]
    pub create_time: DateTime,
    #[sea_orm(column_name = "updateTime")]
    pub update_time: DateTime,
    pub available: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
