//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "picture")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pid: String,
    //原图路径
    #[sea_orm(column_type = "Text")]
    pub original: String,
    //缩略图路径
    #[sea_orm(column_type = "Text")]
    pub thumbnail: String,
    //水印图路径
    #[sea_orm(column_type = "Text")]
    pub watermark: String,
    pub size: i64,
    #[sea_orm(column_name = "createTime")]
    pub create_time: DateTime,
    #[sea_orm(column_name = "updateTime")]
    pub update_time: DateTime,
    pub available: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
