//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

// pub use super::oauth::Entity as Oauth;
// pub use super::orders::Entity as Orders;
pub use super::permission::Entity as Permission;
pub use super::picture::Entity as Picture;
// pub use super::real_name::Entity as RealName;
pub use super::share::Entity as Share;
pub use super::user::Entity as User;
pub use super::user_picture::Entity as UserPicture;
