//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "share")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub sid: String,
    pub id: i64,
    pub uid: i64,
    pub password: Option<String>,
    pub downloads: i64,
    #[sea_orm(column_name = "shareMode")]
    pub share_mode: i32,
    pub expiry: i64,
    #[sea_orm(column_name = "createTime")]
    pub create_time: DateTime,
    #[sea_orm(column_name = "updateTime")]
    pub update_time: DateTime,
    pub available: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
